[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "SKIP_ENV_VALIDATION=true DISABLE_ESLINT_PLUGIN=true NEXT_TELEMETRY_DISABLED=1 bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SKIP_ENV_VALIDATION = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
